/// Making up a passphrase for somebody who should not have to.
///
/// # Why this exists
///
/// The unlock screen asks for a passphrase and explains what it protects, and
/// then leaves the hardest part to the person: thinking of one. What people
/// reach for under that pressure is a name, a date, or something they already
/// use, and Argon2id at 64 MiB does not save a passphrase that is in a list.
///
/// So the application offers to make one. Not as a default, because a
/// passphrase somebody cannot remember is a vault they will lose, but as an
/// option next to the field.
///
/// # Why words rather than characters
///
/// `Xk9#mQ2!vR` is 60 bits and unmemorable. Six words from this list is 72
/// bits and can be repeated back after reading it twice. A passphrase that has
/// to be written on paper to survive is worse than a weaker one that does not,
/// because the paper is a copy and this application's whole position is that
/// there are no copies.
///
/// # The arithmetic
///
/// The list holds exactly 4096 words, so each contributes 12 bits: a power of
/// two on purpose, so the index is a whole number of bits and there is no
/// modulo bias to argue about.
///
///   four words    48 bits
///   five words    60 bits
///   six words     72 bits, the default here
///
/// That is the strength of the passphrase itself. What an attacker with the
/// device faces on top of it is Argon2id at 64 MiB per guess.
///
/// # Where the words came from
///
/// Filtered from `/usr/share/dict/american-english`, which the `wamerican`
/// package records as explicitly placed in the public domain: no attribution
/// required, no licence to carry, nothing to pay.
///
/// Four to seven letters, lowercase, no proper nouns, no plural whose singular
/// is also present, and nothing crude. A passphrase gets read aloud down a
/// phone line, and every one of those filters exists so that goes well.
library;

import 'dart:math';

/// Words per passphrase by default. Six is 72 bits.
const int defaultWordCount = 6;

/// Bits of entropy in a passphrase of [words] words from this list.
int entropyBits(int words) => words * 12;

/// Make one.
///
/// [Random.secure] rather than [Random], and not as a formality: the default
/// generator is seeded predictably enough that two devices starting at the same
/// moment can produce the same sequence, and a guessable passphrase is a vault
/// somebody else can open.
String generatePassphrase({int words = defaultWordCount}) {
  final random = Random.secure();
  return List.generate(words, (_) => _words[random.nextInt(_words.length)])
      .join(' ');
}

/// 4096 words, so each is exactly 12 bits.
const List<String> _words = [
  'abating', 'abed', 'abhor', 'ablaze', 'abloom', 'abreast', 'abscess', 'absence',
  'absent', 'abuse', 'acacia', 'accede', 'acceded', 'accent', 'accept', 'accurst',
  'aced', 'acerbic', 'acetic', 'ached', 'aching', 'acidly', 'acne', 'acrylic',
  'action', 'acute', 'adamant', 'added', 'addend', 'addenda', 'adder', 'address',
  'adduce', 'adieux', 'adjunct', 'adjust', 'adman', 'admiral', 'admirer', 'adobe',
  'adopted', 'adoring', 'adrenal', 'adroit', 'advised', 'adviser', 'aerated', 'affable',
  'affirm', 'afire', 'afoul', 'afraid', 'after', 'agent', 'agleam', 'aglow',
  'agonies', 'ahead', 'ailed', 'aileron', 'ailing', 'aims', 'aired', 'airiest',
  'airmail', 'airway', 'airy', 'akin', 'alarmed', 'alcohol', 'alcove', 'ales',
  'alfalfa', 'alibi', 'alines', 'alit', 'alive', 'alley', 'allies', 'allured',
  'already', 'also', 'alum', 'alumna', 'alumni', 'alumnus', 'amalgam', 'amass',
  'amazed', 'ambled', 'amend', 'amigo', 'amir', 'amiss', 'ammonia', 'amoebae',
  'amongst', 'amply', 'ampul', 'amputee', 'amuck', 'analog', 'anatomy', 'anchor',
  'andiron', 'anemic', 'angrily', 'angry', 'angst', 'animal', 'anime', 'anneal',
  'annexed', 'annoy', 'annoyed', 'annul', 'annular', 'anon', 'antacid', 'anted',
  'anteing', 'anthill', 'anthrax', 'antic', 'antigen', 'antler', 'anvil', 'anyhow',
  'apart', 'apathy', 'apices', 'aplenty', 'appall', 'appeal', 'appease', 'append',
  'apples', 'apply', 'appoint', 'approve', 'aptest', 'aquifer', 'arbutus', 'arcade',
  'arching', 'archive', 'arena', 'argon', 'argot', 'aria', 'arid', 'armada',
  'armies', 'arming', 'armsful', 'around', 'arrived', 'arsenal', 'arson', 'artery',
  'artier', 'artist', 'artless', 'ascetic', 'ashcan', 'ashier', 'ashing', 'aspect',
  'aspens', 'aspired', 'assent', 'asshole', 'assuage', 'astral', 'astute', 'asylum',
  'atavism', 'athlete', 'atonal', 'atone', 'attired', 'audio', 'avail', 'avenge',
  'avenger', 'averred', 'averted', 'aviator', 'avoid', 'avow', 'avowal', 'avowing',
  'awake', 'award', 'awarded', 'awed', 'awesome', 'awing', 'awls', 'axed',
  'babier', 'babiest', 'babying', 'babysat', 'backer', 'backhoe', 'bade', 'bags',
  'bailing', 'baiting', 'bake', 'balking', 'balling', 'balloon', 'baloney', 'balsam',
  'banal', 'banana', 'band', 'bandage', 'bandied', 'bandies', 'banding', 'bandit',
  'bane', 'banjo', 'banked', 'banker', 'bantam', 'barb', 'barbed', 'barbing',
  'bare', 'bared', 'barked', 'barking', 'barn', 'barrack', 'barrio', 'barroom',
  'base', 'baseman', 'bash', 'basin', 'basis', 'basking', 'basses', 'bassist',
  'bast', 'baste', 'basting', 'bastion', 'batch', 'bate', 'bathos', 'bathtub',
  'battery', 'battled', 'bawdy', 'bawling', 'bayonet', 'bayou', 'bazooka', 'beaded',
  'beak', 'beaker', 'beaned', 'bearer', 'bearish', 'beast', 'beastly', 'beat',
  'beaux', 'bebop', 'becalm', 'became', 'bedded', 'bedevil', 'bedlam', 'beefed',
  'beefing', 'beefy', 'beeline', 'beeped', 'beeping', 'beer', 'bees', 'beet',
  'begat', 'beguile', 'behead', 'behest', 'belched', 'belied', 'belief', 'believe',
  'bellhop', 'belling', 'belt', 'belting', 'bemuse', 'bemused', 'bending', 'beneath',
  'benefit', 'benign', 'beret', 'berried', 'beryls', 'bespeak', 'bestir', 'betake',
  'bethink', 'betook', 'betray', 'bets', 'betting', 'bettor', 'between', 'beveled',
  'bevies', 'bewail', 'biases', 'bidder', 'biff', 'biffed', 'bigness', 'bike',
  'bikini', 'bilked', 'bindery', 'binding', 'binged', 'bins', 'biology', 'biped',
  'biplane', 'birches', 'birded', 'birding', 'biscuit', 'bisect', 'bismuth', 'bitter',
  'bizarre', 'blacken', 'bladder', 'blammo', 'blanch', 'blanked', 'blanket', 'blare',
  'blaring', 'blast', 'blat', 'blatant', 'blazed', 'blazing', 'bleeder', 'blench',
  'bless', 'blest', 'blew', 'blinder', 'blintz', 'blither', 'blitzes', 'block',
  'blocked', 'blot', 'blotted', 'blow', 'blowing', 'blowout', 'blowzy', 'blubber',
  'bluest', 'bluffed', 'bluish', 'blurred', 'blusher', 'boar', 'board', 'boaster',
  'boat', 'boater', 'bobbed', 'bobbing', 'bobcat', 'bode', 'bogie', 'bogon',
  'bogus', 'bola', 'bolder', 'boldest', 'bole', 'boll', 'bolt', 'bomb',
  'bombed', 'bonanza', 'bonds', 'bonfire', 'bonnet', 'boob', 'boobing', 'boogied',
  'bookie', 'bookish', 'boorish', 'boos', 'boot', 'bore', 'bored', 'borer',
  'bosom', 'bosses', 'bossier', 'bossing', 'botched', 'both', 'bought', 'bouquet',
  'bovine', 'bowl', 'boxcar', 'boxed', 'boycott', 'boys', 'braise', 'brash',
  'bravely', 'braving', 'brawn', 'breach', 'break', 'breakup', 'breeder', 'breezy',
  'bridge', 'bridled', 'briefly', 'brig', 'briskly', 'bromide', 'bronchi', 'brooder',
  'broth', 'browner', 'browser', 'bruised', 'brunch', 'brunt', 'brushes', 'brusque',
  'brute', 'bubble', 'bubbled', 'bucks', 'buff', 'bugbear', 'buggers', 'buggies',
  'buggy', 'bulged', 'bulgy', 'bulked', 'bullet', 'bulwark', 'bummest', 'bums',
  'bunging', 'bungler', 'burden', 'bureau', 'burgle', 'burka', 'burnout', 'burst',
  'burying', 'busboy', 'bushier', 'bushman', 'busied', 'busily', 'busses', 'busting',
  'busy', 'busying', 'butch', 'butlers', 'buzzing', 'bylaw', 'byline', 'bypass',
  'cabbage', 'cabbed', 'cached', 'cactus', 'cadaver', 'caddish', 'cadenza', 'cagiest',
  'cahoot', 'caisson', 'caking', 'caliper', 'calked', 'calling', 'calming', 'calved',
  'calyces', 'calyx', 'cambium', 'campier', 'canasta', 'candid', 'cannily', 'canning',
  'canny', 'canted', 'cantons', 'cantors', 'canyon', 'capably', 'capped', 'captive',
  'caracul', 'carat', 'carbine', 'carboy', 'carded', 'cargoes', 'caribou', 'caroler',
  'carols', 'carotid', 'carport', 'carries', 'carrot', 'carting', 'carved', 'casein',
  'cashier', 'cashing', 'castoff', 'catbird', 'catchy', 'catered', 'caterer', 'cattail',
  'catwalk', 'caucus', 'causal', 'cavemen', 'cavil', 'cawed', 'ceding', 'cement',
  'centaur', 'ceramic', 'cesium', 'chafed', 'chafing', 'chain', 'chalice', 'chalk',
  'chalked', 'chalky', 'chammy', 'chamoix', 'chances', 'chantey', 'chapped', 'chapt',
  'char', 'charmer', 'charred', 'chased', 'chatted', 'chef', 'cheroot', 'chid',
  'chided', 'chief', 'chiller', 'chime', 'chimney', 'chinned', 'chip', 'chirrup',
  'chisel', 'chit', 'choked', 'chomp', 'choosy', 'chop', 'choppy', 'chore',
  'chorus', 'chucked', 'chunk', 'cicadae', 'cigaret', 'cinched', 'cinches', 'circle',
  'cistern', 'citric', 'civic', 'civies', 'clack', 'clam', 'clammy', 'clamor',
  'clan', 'clap', 'clapped', 'clapper', 'clarify', 'clasp', 'class', 'classed',
  'clawing', 'cleanup', 'clearly', 'cleft', 'clergy', 'clerk', 'clever', 'clew',
  'client', 'climax', 'climb', 'cling', 'clink', 'clipped', 'clocked', 'clod',
  'clog', 'clogged', 'cloning', 'clop', 'close', 'closer', 'cloth', 'clothed',
  'clotted', 'cloture', 'clouded', 'cloudy', 'clouted', 'cloying', 'cluck', 'clunk',
  'clutter', 'clxiv', 'coaches', 'coarser', 'coast', 'coastal', 'coaxing', 'cobble',
  'cobbled', 'cobbler', 'cobra', 'cobs', 'cocci', 'coccus', 'cockade', 'cockier',
  'cocking', 'cocky', 'coda', 'codeine', 'codfish', 'codify', 'cods', 'coed',
  'coerced', 'coeval', 'coffer', 'coffin', 'cohered', 'coif', 'coifed', 'coitus',
  'colic', 'colloid', 'colony', 'colts', 'combo', 'comely', 'comfier', 'coming',
  'compact', 'compel', 'complex', 'conceal', 'concern', 'concert', 'concur', 'condole',
  'conduce', 'cone', 'confirm', 'congaed', 'congeal', 'congest', 'conic', 'conj',
  'conk', 'connote', 'consed', 'consign', 'consult', 'contd', 'contort', 'contour',
  'contuse', 'convene', 'convert', 'convict', 'convoke', 'cooed', 'cookery', 'cookie',
  'cooky', 'coolant', 'coos', 'copy', 'copying', 'cord', 'cordial', 'cording',
  'cork', 'corncob', 'cornea', 'corneal', 'corned', 'cornice', 'cornier', 'cornrow',
  'coroner', 'corrupt', 'cosiest', 'cosmos', 'cosplay', 'costing', 'costly', 'couch',
  'count', 'counted', 'counter', 'country', 'course', 'courser', 'court', 'coven',
  'covey', 'cowbird', 'coxcomb', 'coyest', 'coyly', 'cozen', 'crack', 'cracker',
  'crafted', 'cranked', 'crape', 'crass', 'craters', 'crating', 'craving', 'crayon',
  'creak', 'creamed', 'creed', 'crimped', 'critter', 'crone', 'cronies', 'crosier',
  'crossly', 'crowd', 'crudest', 'cruised', 'cruller', 'crumpet', 'crusade', 'crusty',
  'crutch', 'cruxes', 'crybaby', 'cryptic', 'cube', 'cubic', 'cubs', 'cuckoo',
  'cuddle', 'cues', 'cuff', 'culling', 'culotte', 'culvert', 'cumquat', 'cumuli',
  'cunning', 'cupful', 'cupids', 'cupped', 'cupping', 'curb', 'curd', 'curdle',
  'curing', 'curious', 'curly', 'current', 'curried', 'curries', 'cursive', 'curtain',
  'curtest', 'curtsey', 'curve', 'curved', 'curving', 'cushy', 'cuss', 'custard',
  'cute', 'cutlass', 'cutoff', 'cuts', 'cutter', 'cutting', 'cymbal', 'cynic',
  'czarina', 'dabbled', 'daddies', 'dads', 'dafter', 'dahlia', 'dailies', 'dally',
  'dammed', 'damns', 'damsel', 'danced', 'dancing', 'dandled', 'danger', 'darned',
  'darning', 'dart', 'dated', 'daunted', 'dauphin', 'daybed', 'daytime', 'dazed',
  'dded', 'dearer', 'deaths', 'debated', 'debris', 'debug', 'debunk', 'decamp',
  'deceit', 'decent', 'decline', 'deejay', 'deepen', 'defame', 'default', 'defect',
  'defense', 'defies', 'defray', 'defy', 'degree', 'deities', 'delint', 'deltas',
  'deluxe', 'demo', 'demonic', 'demurer', 'denied', 'denim', 'denote', 'denser',
  'dented', 'dentine', 'denuded', 'deny', 'depart', 'depict', 'deposit', 'depot',
  'deprive', 'dept', 'deputy', 'derail', 'derange', 'descry', 'desktop', 'dessert',
  'detail', 'deter', 'develop', 'device', 'devoid', 'dewlap', 'dharma', 'dialog',
  'dials', 'diamond', 'diaper', 'diced', 'dicker', 'dickey', 'dickie', 'dicky',
  'diddle', 'dieting', 'digging', 'dignify', 'digraph', 'digs', 'dilly', 'dimming',
  'dimness', 'dined', 'diner', 'diocese', 'diorama', 'dioxin', 'diploma', 'dips',
  'dirks', 'dirties', 'disband', 'disco', 'disdain', 'disk', 'dissing', 'distant',
  'distill', 'disuse', 'disused', 'ditto', 'divan', 'diver', 'divide', 'divider',
  'divined', 'divulge', 'divvies', 'dock', 'docking', 'dodgier', 'dodging', 'does',
  'doffing', 'doled', 'dolled', 'dolmen', 'dons', 'donut', 'doped', 'dopy',
  'dork', 'dosage', 'dotting', 'doubt', 'douche', 'doughy', 'dourly', 'dowager',
  'dowdy', 'downier', 'dowse', 'doyen', 'drab', 'drachma', 'draftee', 'drafty',
  'drainer', 'drapery', 'draping', 'draw', 'drawer', 'dread', 'dreaded', 'dredged',
  'dress', 'dresser', 'dressy', 'drily', 'drink', 'dripped', 'drivel', 'droll',
  'drone', 'drooped', 'droplet', 'dropper', 'drove', 'drover', 'drowsed', 'drudged',
  'drudges', 'drug', 'drugged', 'druids', 'drum', 'drummed', 'drys', 'drywall',
  'duality', 'dubbing', 'duchy', 'ducting', 'dudgeon', 'duding', 'duds', 'duelled',
  'dukes', 'dumped', 'dumpy', 'dune', 'dungeon', 'dunked', 'dunno', 'duns',
  'duodena', 'duping', 'duskier', 'dusky', 'dusting', 'duty', 'dyadic', 'dyers',
  'earmark', 'earplug', 'earring', 'earwax', 'ease', 'eased', 'easiest', 'ebbing',
  'edge', 'edged', 'edict', 'edified', 'edifies', 'editing', 'eery', 'efface',
  'effigy', 'egress', 'eider', 'eject', 'ejected', 'elated', 'elbow', 'elect',
  'elegy', 'elevate', 'eleven', 'elide', 'elided', 'elision', 'elitism', 'elks',
  'ells', 'elope', 'eluded', 'eluding', 'embassy', 'embed', 'embody', 'emend',
  'emended', 'emir', 'emirate', 'emit', 'emitted', 'emoji', 'emotion', 'employ',
  'emptily', 'emulate', 'emusic', 'enable', 'enclave', 'encoder', 'encore', 'endemic',
  'endive', 'endow', 'endued', 'enduing', 'engaged', 'engorge', 'enmesh', 'ennui',
  'enquiry', 'enrol', 'ensign', 'ensue', 'enthuse', 'entrant', 'entropy', 'enure',
  'envoy', 'envy', 'epilog', 'epoxies', 'equably', 'equine', 'equinox', 'equip',
  'erasure', 'erectly', 'erode', 'eroding', 'erotic', 'erotica', 'errant', 'errata',
  'erupt', 'esquire', 'essay', 'essence', 'etch', 'etching', 'eulogy', 'euro',
  'evened', 'evening', 'eves', 'evident', 'evil', 'evilly', 'evince', 'evoked',
  'evolved', 'ewer', 'ewes', 'except', 'excise', 'excite', 'excited', 'excreta',
  'excuse', 'exhume', 'exiled', 'existed', 'expiry', 'explain', 'extra', 'extract',
  'eyebrow', 'eyelash', 'eyesore', 'factor', 'factory', 'fagged', 'fags', 'fainted',
  'faintly', 'faker', 'fallacy', 'false', 'falter', 'fanboy', 'fancied', 'fanfare',
  'fang', 'fanning', 'farm', 'farrows', 'farther', 'fatal', 'fatally', 'fatness',
  'fattier', 'fatties', 'faunae', 'favor', 'feather', 'feature', 'fecal', 'fecund',
  'federal', 'feedbag', 'feeding', 'feign', 'feint', 'feline', 'feller', 'felon',
  'felony', 'felt', 'felted', 'fenced', 'fennel', 'fens', 'feral', 'fertile',
  'fervor', 'feta', 'feting', 'fetlock', 'fetter', 'fetus', 'fetuses', 'feud',
  'fiasco', 'fibbed', 'fibbing', 'fibroid', 'fibula', 'fibulae', 'fiction', 'fiddler',
  'fiery', 'fife', 'fifties', 'figs', 'filched', 'filches', 'filly', 'find',
  'finder', 'finding', 'fins', 'fire', 'firearm', 'firefly', 'firmed', 'firmest',
  'fishers', 'fishing', 'fission', 'fistful', 'fitful', 'fitted', 'fizzing', 'fizzle',
  'fizzled', 'flaccid', 'flack', 'flag', 'flair', 'flaking', 'flaky', 'flambes',
  'flame', 'flamed', 'flaming', 'flanked', 'flannel', 'flapper', 'flash', 'flasher',
  'flatbed', 'flaunt', 'fleeing', 'fleshes', 'flew', 'flexing', 'flies', 'flints',
  'flipper', 'floated', 'floater', 'flop', 'flowed', 'flowery', 'flowing', 'flown',
  'flue', 'fluffy', 'fluidly', 'flukier', 'flurry', 'fluted', 'flutter', 'flying',
  'flyover', 'foal', 'foaled', 'fobs', 'focal', 'focuses', 'foetus', 'foible',
  'folk', 'follow', 'fondled', 'fondu', 'font', 'fool', 'foolish', 'footman',
  'foppish', 'forayed', 'forbear', 'forbid', 'forbore', 'foreign', 'foremen', 'forged',
  'forger', 'forging', 'format', 'formed', 'forte', 'fortify', 'forward', 'fosters',
  'foulest', 'fouling', 'found', 'founder', 'foundry', 'fourth', 'foxed', 'frack',
  'fracked', 'frat', 'fraying', 'freaky', 'freckle', 'freedom', 'freely', 'fresh',
  'fresher', 'fretful', 'fries', 'frieze', 'frigid', 'frill', 'frisk', 'frizzy',
  'frogman', 'frogmen', 'frosted', 'froth', 'frothy', 'frozen', 'frugal', 'fruity',
  'fryer', 'frying', 'fuchsia', 'fucked', 'fucker', 'fucks', 'fuddled', 'fudge',
  'fuel', 'fulfil', 'fullest', 'fully', 'fulness', 'fuming', 'fund', 'funding',
  'fungal', 'fungous', 'fungus', 'funkier', 'funnily', 'furor', 'furred', 'furrier',
  'furs', 'fuse', 'fusing', 'fuss', 'fussed', 'fusses', 'fussing', 'futzes',
  'fuze', 'fuzing', 'fuzzed', 'gabbing', 'gabbled', 'gables', 'gadget', 'gaff',
  'gaffe', 'gagging', 'gaiety', 'gaily', 'gaining', 'gainsay', 'gaiter', 'gales',
  'gallant', 'galley', 'gallop', 'gallows', 'gals', 'gamed', 'gamely', 'gamer',
  'gamey', 'gamier', 'gamy', 'ganging', 'gape', 'gaps', 'garbing', 'garbled',
  'gargle', 'garment', 'garotte', 'gaseous', 'gasping', 'gaucho', 'gauged', 'gauging',
  'gauzier', 'gawky', 'gayety', 'gays', 'gaze', 'gazebo', 'gelded', 'gems',
  'generic', 'gentled', 'genus', 'gesture', 'ghost', 'ghosted', 'gibber', 'gibbons',
  'gibe', 'giddier', 'gigged', 'gigging', 'giggle', 'giggler', 'gimme', 'gird',
  'girdle', 'girth', 'given', 'giving', 'gizzard', 'glacier', 'gladder', 'gladly',
  'glamor', 'glamour', 'gland', 'glare', 'glared', 'glaring', 'glassed', 'glasses',
  'glazier', 'glazing', 'gleam', 'gleeful', 'glib', 'glimpse', 'glop', 'gloving',
  'glower', 'glowing', 'glue', 'glummer', 'glutton', 'gnashed', 'gnashes', 'gnat',
  'gnawn', 'goad', 'goaded', 'gobbed', 'gobble', 'gobbler', 'goblet', 'gobs',
  'godlier', 'gods', 'goiter', 'goitre', 'gold', 'golfed', 'golfer', 'gollies',
  'gone', 'gong', 'goober', 'goodby', 'goodly', 'goofed', 'googled', 'googles',
  'gooiest', 'gotcha', 'goutier', 'govt', 'graced', 'graded', 'grainy', 'grammar',
  'grander', 'grandly', 'granola', 'granted', 'granule', 'grape', 'graphed', 'graphic',
  'grasp', 'grasped', 'graved', 'graver', 'gravest', 'graving', 'gravity', 'graying',
  'grays', 'great', 'greed', 'greedy', 'grep', 'grepped', 'greyer', 'grill',
  'grille', 'grilled', 'grimace', 'grime', 'grinned', 'grisly', 'groan', 'groaned',
  'grocer', 'groggy', 'groomed', 'groove', 'groping', 'grouch', 'grouped', 'grow',
  'grower', 'grown', 'growth', 'grub', 'grubbed', 'grudge', 'grue', 'guard',
  'guava', 'guest', 'guiding', 'guild', 'guilder', 'guile', 'guilt', 'guineas',
  'guitar', 'gulag', 'gulches', 'gullet', 'gullies', 'gulling', 'gummed', 'gunfire',
  'gunmen', 'guppies', 'gurgle', 'gurney', 'gushed', 'gusted', 'gusto', 'gutsier',
  'gutted', 'guying', 'guzzled', 'gybed', 'gyrated', 'habit', 'habitat', 'haddock',
  'haiku', 'haired', 'halfway', 'haloes', 'halt', 'halter', 'halting', 'halving',
  'hamlets', 'handbag', 'handily', 'handle', 'handler', 'handset', 'hanging', 'hanks',
  'hapless', 'happier', 'harass', 'harked', 'harken', 'harking', 'harmful', 'harness',
  'harpist', 'harried', 'hash', 'hasten', 'hasting', 'hate', 'hater', 'hating',
  'hatting', 'haunt', 'havoc', 'hawing', 'haze', 'hazmat', 'headed', 'headier',
  'heads', 'heal', 'health', 'heaping', 'hearsay', 'heart', 'hearth', 'heated',
  'heathen', 'heaths', 'heave', 'heaven', 'hedging', 'heinous', 'heir', 'helix',
  'helped', 'hemmed', 'hemp', 'hems', 'henna', 'henpeck', 'herbage', 'hereby',
  'herein', 'hereof', 'heretic', 'heroes', 'heroic', 'hewing', 'hexagon', 'hexing',
  'hiccup', 'hick', 'hideous', 'higher', 'highly', 'highway', 'hiker', 'hinder',
  'hint', 'hipped', 'hippie', 'hisses', 'hissing', 'history', 'hitch', 'hoagy',
  'hoarder', 'hoary', 'hoax', 'hoaxer', 'hobbit', 'hobnail', 'hoboes', 'hock',
  'hoedown', 'hoggish', 'hold', 'holdup', 'holed', 'holier', 'homed', 'homers',
  'homiest', 'homing', 'homonym', 'honcho', 'hone', 'honed', 'honest', 'honesty',
  'hooded', 'hoodlum', 'hoodoo', 'hooey', 'hoofed', 'hook', 'hooking', 'hoot',
  'hootch', 'hooted', 'hopes', 'hoping', 'hornet', 'hornier', 'horrify', 'hosing',
  'hostage', 'hostess', 'hostile', 'houmus', 'hounded', 'hove', 'howl', 'hubbies',
  'hubby', 'hubs', 'huddle', 'huffily', 'hugely', 'hugged', 'hulled', 'hulls',
  'humanly', 'humbug', 'humerus', 'humored', 'hunch', 'hunker', 'hunts', 'hurdle',
  'hurdled', 'hurdler', 'hurler', 'hurried', 'hurt', 'hurtle', 'husker', 'husking',
  'hutch', 'hydrant', 'hyena', 'hymens', 'hymn', 'hymned', 'hyphen', 'hypo',
  'iamb', 'ibex', 'ibices', 'iceberg', 'icing', 'idled', 'idolize', 'iffier',
  'ignite', 'ignited', 'ignore', 'ills', 'imagine', 'imam', 'imbed', 'imbue',
  'immerse', 'impala', 'impede', 'impinge', 'impious', 'implied', 'implies', 'imply',
  'impure', 'inane', 'inanest', 'inanity', 'inapt', 'inborn', 'inbound', 'inbox',
  'inbreed', 'inced', 'incline', 'include', 'indigo', 'induce', 'induced', 'indue',
  'ineptly', 'inexact', 'infancy', 'inflame', 'inflate', 'inflict', 'inform', 'infuse',
  'ingrain', 'inhaled', 'inhuman', 'initio', 'inject', 'injure', 'inking', 'inlaid',
  'inlet', 'inmate', 'innate', 'inner', 'inroad', 'insane', 'insaner', 'insect',
  'insigne', 'insofar', 'inspect', 'instant', 'insult', 'insured', 'insurer', 'intact',
  'intend', 'intern', 'intone', 'intoned', 'intrust', 'intuit', 'inuring', 'invaded',
  'invited', 'ioctl', 'iodine', 'iodize', 'ions', 'iota', 'ironing', 'islet',
  'isms', 'isobar', 'isotope', 'itchier', 'item', 'iterate', 'jabber', 'jabbing',
  'jackal', 'jackdaw', 'jagged', 'jams', 'japans', 'japing', 'jargon', 'jarring',
  'jaunted', 'jazzes', 'jeez', 'jejune', 'jell', 'jest', 'jetted', 'jibbed',
  'jibed', 'jiffies', 'jiggle', 'jigsaw', 'jihad', 'jilt', 'jilted', 'jingle',
  'jinx', 'jinxed', 'jobber', 'jobless', 'jocund', 'jointed', 'joking', 'jolting',
  'joshes', 'joshing', 'jotted', 'journal', 'joyous', 'joyride', 'jugged', 'jugging',
  'juggler', 'jugular', 'juicer', 'juicily', 'jumpier', 'junco', 'juncoes', 'junked',
  'junkie', 'junky', 'jury', 'juster', 'justify', 'justly', 'jute', 'kahuna',
  'karaoke', 'katydid', 'keener', 'keening', 'keeping', 'kelp', 'kenned', 'kestrel',
  'ketch', 'ketchup', 'keyhole', 'keyword', 'khaki', 'khans', 'kidnap', 'killed',
  'kills', 'kiln', 'kilt', 'kilter', 'kindly', 'kingly', 'kinsman', 'kisses',
  'kitten', 'kiwi', 'klutzes', 'kneaded', 'kneecap', 'knights', 'knitted', 'knives',
  'knot', 'knuckle', 'koala', 'kookie', 'kroner', 'kudos', 'kudzu', 'labia',
  'labial', 'laborer', 'labs', 'lace', 'laddie', 'laden', 'ladling', 'lambast',
  'lambs', 'lamprey', 'lams', 'lanker', 'lantern', 'lapping', 'lapse', 'larceny',
  'larch', 'lard', 'large', 'largest', 'lariat', 'larynx', 'lasagna', 'laser',
  'late', 'lather', 'lathing', 'latter', 'lattice', 'lauding', 'lawful', 'laxness',
  'layman', 'lazied', 'lazing', 'leafing', 'leafy', 'leanest', 'leapt', 'lease',
  'leashed', 'leashes', 'leasing', 'leaved', 'ledger', 'leek', 'legal', 'legate',
  'leggin', 'legging', 'leggy', 'legroom', 'lemony', 'lemur', 'lender', 'lengthy',
  'lenient', 'lentil', 'lesser', 'lest', 'letdown', 'lettuce', 'levying', 'liaise',
  'libeled', 'liberal', 'libido', 'license', 'lichee', 'lidded', 'lids', 'lighter',
  'lignite', 'lilies', 'lilt', 'limb', 'limier', 'limiest', 'linage', 'lineal',
  'linear', 'liner', 'lingual', 'linker', 'linking', 'liqueur', 'lissom', 'list',
  'listed', 'listen', 'listing', 'lite', 'liter', 'lithium', 'littler', 'liturgy',
  'live', 'livest', 'llano', 'load', 'loaf', 'loafing', 'loam', 'loaning',
  'loathe', 'lobbied', 'lobbing', 'lobed', 'locally', 'locket', 'locking', 'locust',
  'lodging', 'loft', 'loge', 'logjam', 'lolled', 'lolling', 'lone', 'longed',
  'look', 'looking', 'lookup', 'loopy', 'loosed', 'loosely', 'loosest', 'loped',
  'lopped', 'lore', 'losses', 'lottery', 'lounge', 'lousier', 'lovely', 'lowdown',
  'lowish', 'lows', 'loxes', 'loyally', 'lubed', 'luckily', 'luggage', 'lugged',
  'lullaby', 'lulled', 'lumped', 'lumping', 'lumpish', 'lunched', 'lunged', 'lupin',
  'lurches', 'lurking', 'luster', 'lustier', 'luxury', 'lxiv', 'lymph', 'macho',
  'madmen', 'maggot', 'magnify', 'mailbox', 'mailmen', 'maize', 'malady', 'mallard',
  'mallet', 'malware', 'manacle', 'managed', 'manager', 'manatee', 'mandate', 'mangy',
  'manner', 'mans', 'mansard', 'mantles', 'mapper', 'marabou', 'marched', 'marinas',
  'markup', 'marmot', 'marshes', 'marshy', 'marten', 'martyr', 'mash', 'mashing',
  'mashup', 'masking', 'massive', 'mated', 'matrix', 'matted', 'matzoh', 'matzot',
  'mauled', 'maunder', 'maybe', 'mayfly', 'meadow', 'meander', 'meaner', 'measles',
  'meat', 'meaty', 'meddled', 'mediate', 'medical', 'medley', 'meeker', 'melanin',
  'melded', 'member', 'menaced', 'menage', 'mended', 'menfolk', 'mere', 'merely',
  'merge', 'merged', 'mesas', 'mess', 'messy', 'meted', 'metered', 'meting',
  'mettle', 'mewing', 'mewl', 'mewled', 'miaowed', 'mica', 'middies', 'middle',
  'mien', 'migrate', 'miked', 'mildly', 'miler', 'milky', 'millers', 'million',
  'mincing', 'mind', 'mingle', 'mingled', 'minimum', 'minted', 'mintier', 'minty',
  'minuend', 'minus', 'minxes', 'mirage', 'mire', 'mired', 'misdeed', 'misdoes',
  'misfit', 'misrule', 'missile', 'mistier', 'misting', 'misuse', 'mitered', 'mixes',
  'mixing', 'mobiles', 'mocker', 'modal', 'modern', 'mods', 'modulus', 'moire',
  'moldier', 'molls', 'mollusc', 'molten', 'monied', 'moniker', 'monocle', 'mooched',
  'mooches', 'moodier', 'mooing', 'moonlit', 'moons', 'mooring', 'mooted', 'mooting',
  'mops', 'morally', 'morbid', 'morgue', 'morn', 'mossier', 'most', 'motif',
  'mounts', 'mourned', 'mousey', 'mousing', 'mouth', 'mouthed', 'mowed', 'mucous',
  'muddle', 'muesli', 'mugged', 'muggle', 'mulch', 'multi', 'mummy', 'munches',
  'murders', 'murmur', 'muscle', 'mused', 'museum', 'mushier', 'music', 'must',
  'mustang', 'muted', 'mutest', 'myopic', 'mystify', 'nabbed', 'nacre', 'naiad',
  'namely', 'naphtha', 'nappies', 'napping', 'naps', 'narrate', 'narrow', 'narwhal',
  'nasally', 'nascent', 'native', 'naught', 'nave', 'navel', 'navies', 'navy',
  'neater', 'neath', 'nebular', 'necktie', 'need', 'needed', 'needier', 'needing',
  'neighed', 'nerdy', 'nerved', 'nest', 'nestled', 'nets', 'netter', 'nettle',
  'neural', 'newness', 'newsman', 'newsmen', 'newt', 'newtons', 'nibs', 'niche',
  'nicked', 'nicking', 'nickle', 'nifty', 'niggard', 'nigger', 'nightly', 'nimble',
  'nine', 'nipped', 'nippier', 'nippy', 'nitpick', 'nixes', 'nodal', 'nods',
  'noes', 'noisier', 'noising', 'noncom', 'nonzero', 'noodle', 'nosiest', 'notify',
  'novae', 'novelty', 'nuance', 'nuanced', 'nudge', 'nudged', 'nudism', 'nudist',
  'numbing', 'numbly', 'nuptial', 'nursed', 'nutria', 'nuttier', 'nuzzle', 'oafish',
  'oaks', 'oasis', 'obeying', 'oboe', 'observe', 'occlude', 'ocelot', 'octal',
  'octet', 'octopi', 'odder', 'oddly', 'odium', 'odor', 'odorous', 'offal',
  'offense', 'offer', 'offs', 'offset', 'oftener', 'ogle', 'ogled', 'ogre',
  'ohms', 'oiling', 'oneness', 'onrush', 'oodles', 'oozed', 'opals', 'opened',
  'openest', 'operand', 'operate', 'opining', 'opuses', 'oracles', 'oral', 'oratory',
  'orchid', 'orcs', 'organdy', 'organic', 'orgies', 'orgy', 'origami', 'orotund',
  'osmosis', 'ossify', 'ouch', 'oust', 'ousted', 'ouster', 'ousting', 'outcrop',
  'outing', 'outlast', 'outlaw', 'outpost', 'output', 'outrage', 'outsell', 'outsold',
  'outward', 'outwear', 'outwit', 'outwore', 'outworn', 'ovation', 'oven', 'overlay',
  'oversee', 'overt', 'overtly', 'overuse', 'owls', 'owned', 'oxymora', 'paces',
  'pacify', 'package', 'paddle', 'paged', 'pages', 'pail', 'pailful', 'painful',
  'paired', 'paisley', 'pale', 'palette', 'pallet', 'pallid', 'palmed', 'palmist',
  'pals', 'palsy', 'paltry', 'panache', 'pander', 'panned', 'pant', 'panther',
  'pantry', 'papa', 'papaw', 'papilla', 'parade', 'parapet', 'parboil', 'parched',
  'parka', 'parked', 'parlor', 'parring', 'parry', 'parson', 'part', 'partied',
  'partook', 'passes', 'passive', 'past', 'pastie', 'patched', 'patchy', 'patella',
  'patient', 'patriot', 'patrol', 'pats', 'patsies', 'patted', 'pave', 'paving',
  'paws', 'payable', 'payment', 'payroll', 'paywall', 'peaked', 'pebble', 'pebbled',
  'pecan', 'peccary', 'pedant', 'peed', 'peering', 'pelvis', 'pence', 'pencil',
  'pennant', 'pens', 'pensive', 'people', 'pepper', 'peppery', 'peps', 'percale',
  'perhaps', 'periled', 'perish', 'perking', 'perky', 'permit', 'perter', 'pervade',
  'peseta', 'pestle', 'petal', 'petard', 'pettily', 'pews', 'pharynx', 'phial',
  'phisher', 'phloem', 'phlox', 'phoebes', 'phone', 'phoned', 'phoneme', 'photon',
  'phrased', 'phyla', 'phylum', 'physic', 'piazze', 'pickaxe', 'picked', 'picker',
  'picking', 'pickup', 'pidgin', 'piecing', 'pigged', 'piggies', 'pigging', 'piglet',
  'pigskin', 'pigtail', 'pilling', 'pillion', 'pillory', 'pimped', 'pimply', 'pine',
  'pinker', 'pinkish', 'pins', 'pinto', 'pipe', 'piper', 'pistol', 'piston',
  'pitches', 'pities', 'pity', 'pixel', 'pizazz', 'placard', 'placket', 'plagues',
  'plaited', 'planter', 'plastic', 'plate', 'platypi', 'playing', 'plead', 'pleader',
  'please', 'pleased', 'plod', 'plodder', 'plop', 'ploy', 'plucky', 'plumb',
  'plunder', 'plunged', 'plunk', 'plush', 'plywood', 'poach', 'podding', 'poesy',
  'poetess', 'pogrom', 'point', 'poker', 'poky', 'polity', 'pollute', 'pols',
  'pomade', 'poncho', 'pond', 'pooches', 'poohing', 'pooling', 'pooping', 'poor',
  'poorly', 'popping', 'posh', 'posies', 'posing', 'posited', 'poss', 'posted',
  'postwar', 'potato', 'potency', 'potent', 'pottery', 'pottier', 'pouch', 'pouted',
  'powder', 'powered', 'powwow', 'poxes', 'praise', 'pram', 'prancer', 'prated',
  'predate', 'preened', 'prepay', 'preppy', 'presage', 'pressed', 'presto', 'presume',
  'pretend', 'pretzel', 'prevue', 'prey', 'preyed', 'pricy', 'priding', 'pries',
  'primacy', 'primed', 'primly', 'printed', 'prison', 'privier', 'probing', 'procure',
  'prodigy', 'product', 'profane', 'profit', 'progeny', 'promo', 'pronged', 'proofed',
  'prophet', 'propped', 'prorate', 'prosaic', 'protean', 'proud', 'prouder', 'provoke',
  'provost', 'proxy', 'prune', 'pruned', 'pruning', 'psalm', 'pshaw', 'psyched',
  'pubs', 'puckish', 'puffing', 'pugs', 'puking', 'pulsate', 'pumice', 'pumping',
  'punchy', 'punkest', 'pupil', 'pupped', 'puppet', 'purge', 'purism', 'purist',
  'purl', 'purring', 'pursued', 'pursuit', 'push', 'putrid', 'putsch', 'putted',
  'putty', 'pwns', 'pyrite', 'quack', 'quad', 'quaffed', 'quail', 'quaked',
  'quark', 'quart', 'quartet', 'quasar', 'quay', 'queasy', 'queenly', 'queer',
  'queerer', 'queerly', 'quell', 'query', 'quick', 'quiet', 'quieter', 'quilted',
  'quilter', 'quipped', 'quit', 'quite', 'quiver', 'quiz', 'rabble', 'raced',
  'raceway', 'rack', 'racy', 'radiant', 'radish', 'raffled', 'raft', 'rafting',
  'ragging', 'ragweed', 'rail', 'raiment', 'rained', 'raja', 'ramify', 'ramp',
  'rampant', 'ranch', 'ranched', 'range', 'rangier', 'ransom', 'rant', 'rapid',
  'rapider', 'rapt', 'rarest', 'raring', 'rashly', 'rasped', 'rated', 'rats',
  'rattled', 'rattler', 'ratty', 'ravine', 'ravish', 'rayon', 'razed', 'razing',
  'razzes', 'readier', 'reagent', 'real', 'realer', 'realign', 'realist', 'ream',
  'reaming', 'reaped', 'rebind', 'rebuilt', 'rebuses', 'recant', 'recent', 'recess',
  'recheck', 'recital', 'recited', 'recoil', 'rector', 'rectory', 'redder', 'reddest',
  'redhead', 'redid', 'redneck', 'redness', 'redone', 'redound', 'redraft', 'redrew',
  'redwood', 'reef', 'reefing', 'reelect', 'refer', 'reflect', 'refresh', 'refuge',
  'refusal', 'refuted', 'regal', 'regaled', 'regalia', 'regret', 'regroup', 'rehash',
  'rehi', 'reject', 'rejoice', 'relaid', 'related', 'relaxed', 'relic', 'remade',
  'remorse', 'removal', 'renal', 'rend', 'rending', 'renewal', 'reopen', 'reorged',
  'repaint', 'repast', 'repeal', 'replace', 'replica', 'replied', 'replies', 'reptile',
  'requiem', 'requite', 'reroute', 'rescuer', 'reserve', 'resided', 'residue', 'resist',
  'resolve', 'resort', 'resound', 'resp', 'respell', 'rest', 'restate', 'restock',
  'restore', 'retaken', 'retched', 'retell', 'rethink', 'retire', 'retold', 'retreat',
  'retrial', 'return', 'retweet', 'retyped', 'reveler', 'revenge', 'revered', 'reveres',
  'reverse', 'revery', 'revised', 'revs', 'reward', 'rework', 'rewrite', 'rewrote',
  'rheum', 'rhodium', 'rhyme', 'rhymed', 'ribald', 'ribbon', 'riced', 'richer',
  'riches', 'richly', 'ricing', 'rickets', 'ricks', 'ridded', 'riddles', 'ridged',
  'ridging', 'rifest', 'riffle', 'riffled', 'rifle', 'rifled', 'right', 'righter',
  'rightly', 'rigid', 'rile', 'rill', 'riming', 'ringed', 'ripely', 'ripest',
  'ripper', 'risen', 'rite', 'ritual', 'riveted', 'rivulet', 'roaches', 'robbing',
  'robe', 'robing', 'robotic', 'robs', 'rocker', 'rocking', 'rodeo', 'rods',
  'rogered', 'roiled', 'roiling', 'roister', 'romper', 'roof', 'roofed', 'rookery',
  'rookie', 'rooming', 'roost', 'rooster', 'rooting', 'rostra', 'rotate', 'rotted',
  'rotund', 'roughen', 'round', 'roundly', 'rout', 'roves', 'rubbing', 'rubric',
  'ruddier', 'rudely', 'rues', 'ruff', 'ruffian', 'ruffing', 'ruffle', 'rugs',
  'ruling', 'rumba', 'rumored', 'rumpus', 'rune', 'runic', 'runnel', 'running',
  'rural', 'rushing', 'rust', 'rustier', 'rustler', 'saber', 'sadism', 'sadness',
  'safer', 'safety', 'saffron', 'sago', 'sailing', 'salad', 'salary', 'saliva',
  'salmon', 'salted', 'salvage', 'salving', 'sanctum', 'sandbar', 'sandbox', 'sanely',
  'sank', 'sappy', 'sarcasm', 'saree', 'sash', 'sass', 'satanic', 'sated',
  'satyr', 'sauna', 'saunter', 'savaged', 'savager', 'save', 'saver', 'savored',
  'savvied', 'sawdust', 'saying', 'scab', 'scad', 'scag', 'scalp', 'scamp',
  'scampi', 'scandal', 'scar', 'scaring', 'scary', 'scented', 'school', 'scoffed',
  'scold', 'scollop', 'scooped', 'scooter', 'scoped', 'scream', 'screen', 'screwed',
  'scrog', 'scull', 'scummed', 'scythed', 'seabird', 'seal', 'sealant', 'sealed',
  'seam', 'seamed', 'seated', 'seceded', 'secrete', 'sect', 'sector', 'secure',
  'secy', 'sedan', 'sedater', 'seducer', 'seedy', 'seeker', 'seeking', 'seem',
  'seen', 'seeping', 'segment', 'seizing', 'selfish', 'send', 'sending', 'sensed',
  'sensual', 'septa', 'sequin', 'seraph', 'serener', 'serf', 'serial', 'serous',
  'serried', 'servant', 'serve', 'service', 'setback', 'setter', 'seventh', 'seventy',
  'severe', 'severer', 'sexier', 'sexily', 'sexism', 'sexist', 'shabby', 'shad',
  'shadow', 'shag', 'shaikh', 'shaker', 'shamed', 'shape', 'share', 'sharia',
  'shark', 'sharpen', 'shaver', 'sheared', 'shed', 'shells', 'shelve', 'shield',
  'shifty', 'shimmy', 'shin', 'shining', 'shiny', 'shits', 'shiver', 'shivery',
  'shlep', 'shlock', 'shocker', 'shoeing', 'shone', 'shooter', 'shopper', 'shore',
  'shored', 'shortly', 'show', 'showed', 'showier', 'showmen', 'showoff', 'showy',
  'shrewd', 'shriek', 'shrine', 'shrive', 'shrivel', 'shroud', 'shudder', 'shun',
  'shushes', 'shyer', 'sibling', 'sibyls', 'sided', 'siding', 'sidle', 'siesta',
  'sieved', 'sigma', 'signet', 'signify', 'silence', 'silica', 'silkier', 'sill',
  'sillier', 'silt', 'simile', 'simper', 'sine', 'sinewy', 'singed', 'single',
  'singled', 'singly', 'sinker', 'sinner', 'siphon', 'sisal', 'sissies', 'sitar',
  'sitcom', 'sited', 'sixes', 'sizable', 'sizer', 'sizing', 'sizzle', 'skater',
  'skating', 'skied', 'skiff', 'skillet', 'skin', 'skip', 'skit', 'skulk',
  'slabbed', 'slack', 'slacked', 'slackly', 'slammer', 'slangy', 'slaver', 'sleeked',
  'sleekly', 'sleeper', 'sleet', 'sleety', 'slick', 'slicked', 'slide', 'slier',
  'slimmed', 'slimmer', 'sloe', 'sloop', 'sloped', 'slosh', 'sloshed', 'slouch',
  'slow', 'slowest', 'slue', 'slued', 'slugged', 'slugger', 'sluice', 'slumdog',
  'slumped', 'slung', 'slushy', 'sluts', 'smack', 'smacker', 'smalls', 'smarted',
  'smarten', 'smashed', 'smelly', 'smirk', 'smit', 'smoothy', 'smother', 'smudgy',
  'smuggle', 'smurf', 'snaked', 'snap', 'snapper', 'snappy', 'snark', 'snarky',
  'snarl', 'snazzy', 'sneak', 'sneer', 'sniping', 'snob', 'snorkel', 'snort',
  'snorted', 'snowier', 'snowing', 'snuff', 'soar', 'sobbing', 'socket', 'sodium',
  'sods', 'softy', 'soggier', 'sojourn', 'solder', 'soldier', 'solemn', 'soli',
  'solider', 'solidly', 'solved', 'sombre', 'somehow', 'sonata', 'sooner', 'soothe',
  'sopping', 'sorcery', 'sorer', 'sorrow', 'sough', 'souping', 'soured', 'sourer',
  'souring', 'soused', 'sousing', 'sows', 'soybean', 'space', 'spacing', 'spacy',
  'spake', 'spandex', 'spangle', 'sparkle', 'spasm', 'spat', 'spate', 'spatula',
  'spayed', 'spaying', 'speak', 'speared', 'special', 'speck', 'specked', 'speckle',
  'sped', 'speed', 'spelled', 'spelt', 'spew', 'spies', 'spigot', 'spiking',
  'spinal', 'spindle', 'spinner', 'spiraea', 'spirit', 'split', 'splodge', 'spoof',
  'spooked', 'spool', 'spoon', 'spore', 'sport', 'spotter', 'spouse', 'sprain',
  'sprat', 'sprawl', 'sprayer', 'spree', 'springy', 'spruced', 'sprucer', 'spume',
  'spumed', 'spur', 'spurn', 'sputum', 'squarer', 'squawk', 'squeal', 'stab',
  'stable', 'stadia', 'staffed', 'stammer', 'stamp', 'stance', 'staph', 'staple',
  'stapler', 'staring', 'starlet', 'starlit', 'startup', 'staved', 'staving', 'staying',
  'steeply', 'steered', 'stellar', 'stench', 'stepped', 'sterile', 'stew', 'steward',
  'stick', 'sticky', 'sties', 'stiffen', 'stifle', 'stifled', 'stigma', 'stilted',
  'stinker', 'stint', 'stipend', 'stodgy', 'stoical', 'stoked', 'stomp', 'stonily',
  'stooge', 'stool', 'stooped', 'stopped', 'stopper', 'storey', 'stormed', 'stoutly',
  'strafe', 'stream', 'strewn', 'strike', 'striker', 'strode', 'stroked', 'stub',
  'stud', 'student', 'stuffy', 'stump', 'styli', 'stylist', 'styptic', 'suave',
  'sublet', 'subsist', 'subsoil', 'subtle', 'subtly', 'succor', 'suckled', 'suds',
  'sudsier', 'sued', 'suffice', 'suffix', 'sugar', 'sullen', 'sullies', 'sundown',
  'sunken', 'sunspot', 'suntan', 'superb', 'supped', 'supply', 'sups', 'surer',
  'surest', 'surfer', 'suspect', 'suspend', 'swab', 'swallow', 'swam', 'swami',
  'sward', 'swarthy', 'swashes', 'swatch', 'swathed', 'swatter', 'sway', 'swear',
  'sweaty', 'sweets', 'swelter', 'swerved', 'swimmer', 'swiped', 'swiping', 'swished',
  'swisher', 'swishes', 'swollen', 'swop', 'sylph', 'sylvan', 'symbol', 'sysop',
  'tabbed', 'tablet', 'tabling', 'taboo', 'tabooed', 'tackled', 'tact', 'tactful',
  'taffy', 'tagging', 'tail', 'tainted', 'takeout', 'talker', 'talking', 'tallied',
  'tallow', 'tally', 'tamer', 'taming', 'tamped', 'tandem', 'tang', 'tangle',
  'tankard', 'tanking', 'tannest', 'tannin', 'tanning', 'tans', 'tansy', 'tantrum',
  'taper', 'taping', 'tapir', 'tapped', 'tardily', 'tardy', 'tarnish', 'tarring',
  'tarter', 'tasking', 'tasting', 'tatted', 'tattle', 'tattled', 'tattoo', 'tatty',
  'taunt', 'taut', 'tauter', 'tautly', 'tawdry', 'taxies', 'taxying', 'teamed',
  'tearful', 'tearing', 'teas', 'tease', 'teased', 'teasel', 'tech', 'tedious',
  'teeming', 'temped', 'tempi', 'tempt', 'tempted', 'tenable', 'tend', 'tens',
  'tensed', 'tensor', 'tenth', 'termite', 'terrify', 'terse', 'tersely', 'texting',
  'that', 'thawed', 'their', 'thereto', 'thicker', 'thicket', 'third', 'thistle',
  'thorium', 'thou', 'thread', 'thresh', 'thrived', 'throat', 'throw', 'thus',
  'thymus', 'tickle', 'tidbit', 'tides', 'tier', 'ties', 'tiff', 'tiffing',
  'tike', 'tilted', 'timber', 'timbre', 'timely', 'timpani', 'tinfoil', 'tinge',
  'tinged', 'tinging', 'tingled', 'tinny', 'tinsel', 'tipi', 'tipping', 'tipsily',
  'tipster', 'tipsy', 'tiptoe', 'tire', 'tireder', 'tithing', 'titled', 'titling',
  'tizzy', 'toasty', 'toddy', 'toed', 'toeing', 'toffee', 'toffy', 'toggled',
  'toiled', 'toiler', 'toking', 'toll', 'tolled', 'tomb', 'tombed', 'tomboy',
  'toms', 'tonal', 'tong', 'tonier', 'toning', 'tons', 'tonsure', 'toolbar',
  'toolbox', 'tooth', 'topaz', 'topic', 'topknot', 'topmast', 'toppled', 'torched',
  'torment', 'torpid', 'torque', 'tors', 'torsi', 'tort', 'torture', 'torus',
  'toss', 'tote', 'touch', 'touched', 'touches', 'toughen', 'tougher', 'tourism',
  'towel', 'towered', 'tows', 'toxic', 'toys', 'tragic', 'trailer', 'traipse',
  'trait', 'tramp', 'trapeze', 'travel', 'treadle', 'treas', 'treed', 'treetop',
  'trek', 'trendy', 'tresses', 'triage', 'tribune', 'tried', 'trilled', 'trimmed',
  'trinket', 'trip', 'triple', 'triply', 'trisect', 'trivet', 'trolly', 'tron',
  'troop', 'trooper', 'tropic', 'tropism', 'trouble', 'trounce', 'troupe', 'trouper',
  'trouser', 'truancy', 'truant', 'trudge', 'trudged', 'truss', 'trusses', 'trusted',
  'tryst', 'tuba', 'tuft', 'tugboat', 'tumbled', 'tumbrel', 'tummies', 'tunic',
  'tunnel', 'tunnies', 'turbot', 'turds', 'turfing', 'turmoil', 'tussock', 'tutor',
  'tweak', 'tweedy', 'twelve', 'twerked', 'twiggy', 'twine', 'twinged', 'twining',
  'twirl', 'twit', 'twofold', 'twos', 'tycoon', 'tyke', 'typeset', 'typify',
  'tyranny', 'tzar', 'umping', 'umpteen', 'unaided', 'unarmed', 'unasked', 'unbar',
  'unbent', 'unblock', 'unbosom', 'unclasp', 'unclear', 'undated', 'undid', 'uneasy',
  'uneaten', 'unfold', 'unguent', 'unhitch', 'unholy', 'unhorse', 'unhurt', 'unicorn',
  'unifies', 'unify', 'unison', 'unlaced', 'unlearn', 'unlock', 'unlucky', 'unmake',
  'unman', 'unmoral', 'unpack', 'unready', 'unsafer', 'unscrew', 'unseal', 'untie',
  'untied', 'untried', 'untrue', 'untruer', 'unused', 'unwed', 'unwise', 'unwound',
  'unwrap', 'unzip', 'upchuck', 'updraft', 'upgrade', 'upload', 'upped', 'upright',
  'urea', 'urinal', 'urns', 'urology', 'usable', 'using', 'uterus', 'vacant',
  'vague', 'vainest', 'valance', 'valeted', 'valid', 'valued', 'vamoose', 'vamping',
  'vanning', 'vans', 'varied', 'varsity', 'vastly', 'vats', 'vector', 'veer',
  'veered', 'veering', 'veiling', 'vein', 'vellum', 'velvety', 'venally', 'vendor',
  'venison', 'verb', 'verbal', 'verbena', 'versed', 'versing', 'version', 'vertex',
  'very', 'vetch', 'vetches', 'veteran', 'veto', 'vetted', 'vetting', 'vexing',
  'vibe', 'vibrant', 'vicar', 'vice', 'victual', 'view', 'viewer', 'vine',
  'vinegar', 'violas', 'violist', 'viral', 'virtual', 'virtue', 'visibly', 'vision',
  'visited', 'vitamin', 'vixen', 'vocalic', 'vocally', 'voguish', 'voice', 'voile',
  'volley', 'volt', 'voltage', 'volubly', 'vouched', 'vouches', 'vowed', 'vows',
  'voyage', 'wacker', 'wacky', 'wader', 'wagered', 'wagged', 'wagging', 'waggish',
  'waggle', 'wagon', 'waking', 'wanked', 'wanking', 'want', 'wanted', 'wanting',
  'wanton', 'warding', 'warhead', 'warier', 'wariest', 'warily', 'warlike', 'warlord',
  'warpath', 'warrens', 'warship', 'wart', 'wartier', 'wartime', 'washer', 'washtub',
  'waspish', 'wastage', 'waster', 'wastrel', 'water', 'weaken', 'weaning', 'wear',
  'wearied', 'wearily', 'weary', 'webbed', 'wedder', 'wedding', 'wedged', 'wedging',
  'weeded', 'weekend', 'weekly', 'weepier', 'weer', 'wees', 'weevil', 'weird',
  'weirder', 'weirdo', 'welched', 'welshed', 'welter', 'welting', 'wench', 'wenches',
  'wending', 'wetter', 'wettest', 'wetware', 'whacker', 'whacky', 'wharf', 'wharves',
  'what', 'whatnot', 'wheal', 'wheaten', 'wheel', 'whelked', 'whew', 'whiffed',
  'whine', 'whippet', 'whir', 'whistle', 'whiter', 'whither', 'whiting', 'whole',
  'wholly', 'whom', 'whoosh', 'whopper', 'whorl', 'wicked', 'wield', 'wife',
  'wigged', 'wiggle', 'wiggled', 'wiggly', 'wight', 'wigs', 'wigwam', 'wiki',
  'wildly', 'wilier', 'wiling', 'willowy', 'wincing', 'wind', 'windbag', 'window',
  'wing', 'winning', 'wino', 'wiped', 'wiping', 'wirier', 'wiring', 'wiser',
  'wisest', 'witched', 'with', 'witness', 'wits', 'witty', 'wizened', 'wizes',
  'wobble', 'woes', 'woks', 'woman', 'wont', 'wooded', 'woodier', 'woodmen',
  'wooer', 'woofed', 'wooly', 'wording', 'worked', 'workmen', 'wormed', 'wormy',
  'worsen', 'wove', 'wows', 'wrack', 'wreathe', 'wreck', 'wrecked', 'wringer',
  'written', 'wrong', 'wryer', 'wryly', 'wuss', 'wusses', 'xcvi', 'xvii',
  'xxxii', 'xxxix', 'xxxv', 'yammer', 'yapped', 'yaps', 'yawed', 'yawl',
  'yaws', 'yeah', 'year', 'yeas', 'yeasty', 'yellow', 'yelp', 'yens',
  'yessed', 'yessing', 'yest', 'yodel', 'yogurt', 'yoked', 'yoking', 'yonder',
  'yowling', 'yucking', 'yucky', 'yummy', 'yuppy', 'zaniest', 'zany', 'zeal',
  'zilch', 'zinc', 'zing', 'zinged', 'zonal', 'zoned', 'zoology', 'zorch',
];
